# Using an autoencode with latent dimensions 32x32x4 (HxWxC)
---
based_on:
  data: data.LSUNchurch256
  model.params.ae_config: ae_config.convae256_32x32x4
  model.params.sde_config: sde_config.VESDE
  model.params.loss_config: loss_config.SDELoss

lightning:
  callbacks:
    image_logger:
      params:
        batch_frequency: 4000 # scales with the inverse batch-size
        use_exponential_steps: False
        min_steps: 5

model:
  base_learning_rate: 1.25e-5
  target: ncsn.models.scorebased.ScoreBasedModel
  params:
    ncsn_config:
      target: ncsn.modules.ncsns.ncsnpp.NCSNpp
      params:
        in_channels: 4
        ch: 128
        ch_mult: [1, 4, 4]
        num_res_blocks: 2
        resolution: 32
        attn_resolutions: [16, 8]
        resblock_type: biggan
        nonlinearity: swish
        embedding_type: fourier
        fourier_scale: 16
        time_conditional: True
        resample_with_conv: True
        fir: True
        fir_kernel: [1, 3, 3, 1]
        weight_init_scale: 0.
        scale_by_sqrt2: True
        scale_output_by_sigma: True
        dropout: 0.

    sampling_kwargs:
      sampling_method: pc
      predictor: reverse_diffusion
      corrector: langevin
      n_steps_each: 1
      shape: [2, 4, 32, 32]
      eps: 1e-5
      snr: 0.16
      noise_removal: True
      continuous: True
