# data base configurations
---
LSUNchurch256:
  data:
    target: cutlit.DataModuleFromConfig
    params:
      batch_size: 16
      num_workers: 8
      train:
        target: ncsn.data.lsun.LSUNChurchesTrain # 256 x 256
      validation:
        target: ncsn.data.lsun.LSUNChurchesValidation # 256 x 256
