# Loss base configurations
---
SDELoss:
  target: ncsn.modules.losses.sde_loss.SDELoss
  params:
    likelihood_weighting: False
    reduce_mean: True

DDPMLoss:
  target: ncsn.modules.losses.ddpm_loss.DDPMLoss
  params:
    reduce_mean: True

SMLDLoss:
  target: ncsn.modules.losses.smld_loss.SMLDLoss
  params:
    reduce_mean: True
