# NCSN base configurations
---
NCSNpp:
  model:
    params:
      ncsn_config:
        target: ncsn.modules.ncsns.ncsnpp.NCSNpp
        params:
          in_channels:
          ch:
          ch_mult:
          num_res_blocks:
          resolution:
          attn_resolutions:
          resblock_type:
          nonlinearity:
          embedding_type:
          fourier_scale:
          time_conditional:
          resample_with_conv:
          fir:
          fir_kernel:
          weight_init_scale:
          scale_by_sqrt2:
          scale_output_by_sigma:
          dropout:
          sigma_min:
          sigma_max:
          num_scales:
